### ISSUE TITLE
Galileo

### ISSUE THREAD

**Issue by piwats** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#109] opened 2016-07-14 13:00 UTC
Hello dear folks, dear BQ staff,

later this year Qualcomm announced, that some of their Snapdragons will get Galileo support.

Do you know if our beloved M5 will also get Galileo support?

Thanks in advance.

**Comment by cmorlok** [comment] 2016-07-14 13:06
Duplicate of #19.

**Closed as completed by cmorlok** 2016-07-14 13:06 UTC
