### ISSUE TITLE
SIM1: No outgoing calls possible while incoming calls work.

### ISSUE THREAD

**Issue by piwats** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#141] opened 2016-11-28 11:49 UTC
CM-14.1, build from 24th Nov. 16:

SIM1 is for voice calls/sms only.
SIM2 is for mobile data only.

In the Settings SIM1 is set to LTE (tried the other options, too), while SIM2 is set to LTE.

SIM1 seems to register in the network, however, a cross is shown above the signal status of SIM1 & the Setting of the default outgoing SIM for voice calls is grayed out.

Incoming calls to SIM1 work.

**Comment by cmorlok** [comment] 2016-11-28 12:38
Cannot reproduce:
* I can call out on both SIMs.
* I can select the default outgoing SIM.

How did you manage to get LTE on SIM2? This is currently broken, SIM2 is 2G only, see #140 

From which version did you update? 13.0 or an unofficial 14.0/14.1?

**Comment by piwats** [comment] 2016-11-28 12:52
I updated to 14.1 sometime last week from a nigthly 13.1 installed on my m5 at that time.

LTE on SIM2 works so far (the speed is there)

In the status of SIM1 the type of the network is shown as GSM (even if in the settings LTE was chosen), in SIM2 as LTE.

**Comment by cmorlok** [comment] 2016-11-28 13:02
Only one SIM (the data SIM) can be connected to 3G/4G. The other SIM is always connected to 2G regardless of the settings (hardware restrictions).

Could you please send me:
* a screenshot of settings -> about -> status -> sim 1 status and sim 2 status
* output of "logcat -d -b main" and "logcat -d -b radio" after a failed call (don't post this here, it might contain sensitive data)

**Comment by cmorlok** [comment] 2016-12-01 06:40
No one else can reproduce this, I will close it now. 

If you are still having this problem with the official Nightly, please re-open the ticket.

**Closed as completed by cmorlok** 2016-12-01 06:40 UTC
Labels: cm-14.1
